backend_homepage:
    pattern:  /
    defaults: { _controller: KailabBackendBundle:Default:index }

# slide

backend_slide_list:
    pattern:  /slide
    defaults: { _controller: KailabBackendBundle:Slide:index }

backend_slide_new:
    pattern:  /slide/new
    defaults: { _controller: KailabBackendBundle:Slide:new }

backend_slide_edit:
    pattern:  /slide/edit/{id}
    defaults: { _controller: KailabBackendBundle:Slide:edit }

backend_slide_save:
    pattern:  /slide/save
    defaults: { _controller: KailabBackendBundle:Slide:save }

backend_slide_delete:
    pattern:  /slide/delete/{id}
    defaults: { _controller: KailabBackendBundle:Slide:delete }

backend_slide_up:
    pattern:  /slide/up/{id}
    defaults: { _controller: KailabBackendBundle:Slide:up }

backend_slide_down:
    pattern:  /slide/down/{id}
    defaults: { _controller: KailabBackendBundle:Slide:down }

backend_slide_toggle:
    pattern:  /slide/toggle/{id}
    defaults: { _controller: KailabBackendBundle:Slide:toggle }

# screenshot

backend_screenshot_list:
    pattern:  /screenshot
    defaults: { _controller: KailabBackendBundle:Screenshot:index }

backend_screenshot_new:
    pattern:  /screenshot/new
    defaults: { _controller: KailabBackendBundle:Screenshot:new }

backend_screenshot_edit:
    pattern:  /screenshot/edit/{id}
    defaults: { _controller: KailabBackendBundle:Screenshot:edit }

backend_screenshot_save:
    pattern:  /screenshot/save
    defaults: { _controller: KailabBackendBundle:Screenshot:save }

backend_screenshot_delete:
    pattern:  /screenshot/delete/{id}
    defaults: { _controller: KailabBackendBundle:Screenshot:delete }

backend_screenshot_image:
    pattern:  /screenshot/image/{id}
    defaults: { _controller: KailabBackendBundle:Screenshot:image }

# app

backend_app_list:
    pattern:  /app
    defaults: { _controller: KailabBackendBundle:App:index }

backend_app_new:
    pattern:  /app/new
    defaults: { _controller: KailabBackendBundle:App:new }

backend_app_edit:
    pattern:  /app/edit/{id}
    defaults: { _controller: KailabBackendBundle:App:edit }

backend_app_save:
    pattern:  /app/save
    defaults: { _controller: KailabBackendBundle:App:save }

backend_app_delete:
    pattern:  /app/delete/{id}
    defaults: { _controller: KailabBackendBundle:App:delete }

backend_app_up:
    pattern:  /app/up/{id}
    defaults: { _controller: KailabBackendBundle:App:up }

backend_app_down:
    pattern:  /app/down/{id}
    defaults: { _controller: KailabBackendBundle:App:down }

backend_app_toggle:
    pattern:  /app/toggle/{id}
    defaults: { _controller: KailabBackendBundle:App:toggle }

# tech

backend_tech_list:
    pattern:  /tech
    defaults: { _controller: KailabBackendBundle:Tech:index }

backend_tech_new:
    pattern:  /tech/new
    defaults: { _controller: KailabBackendBundle:Tech:new }

backend_tech_edit:
    pattern:  /tech/edit/{id}
    defaults: { _controller: KailabBackendBundle:Tech:edit }

backend_tech_save:
    pattern:  /tech/save
    defaults: { _controller: KailabBackendBundle:Tech:save }

backend_tech_delete:
    pattern:  /tech/delete/{id}
    defaults: { _controller: KailabBackendBundle:Tech:delete }

backend_tech_up:
    pattern:  /tech/up/{id}
    defaults: { _controller: KailabBackendBundle:Tech:up }

backend_tech_down:
    pattern:  /tech/down/{id}
    defaults: { _controller: KailabBackendBundle:Tech:down }

backend_tech_toggle:
    pattern:  /tech/toggle/{id}
    defaults: { _controller: KailabBackendBundle:Tech:toggle }

# platform

backend_platform_list:
    pattern:  /platform
    defaults: { _controller: KailabBackendBundle:Platform:index }

backend_platform_new:
    pattern:  /platform/new
    defaults: { _controller: KailabBackendBundle:Platform:new }

backend_platform_edit:
    pattern:  /platform/edit/{id}
    defaults: { _controller: KailabBackendBundle:Platform:edit }

backend_platform_save:
    pattern:  /platform/save
    defaults: { _controller: KailabBackendBundle:Platform:save }

backend_platform_delete:
    pattern:  /platform/delete/{id}
    defaults: { _controller: KailabBackendBundle:Platform:delete }

backend_platform_background:
    pattern:  /platform/{id}/background
    defaults: { _controller: KailabBackendBundle:Platform:background }

backend_platform_icon:
    pattern:  /platform/{id}/icon
    defaults: { _controller: KailabBackendBundle:Platform:icon }

# blog post

backend_blog_post_list:
    pattern:  /blog/post
    defaults: { _controller: KailabBackendBundle:BlogPost:index }

backend_blog_post_new:
    pattern:  /blog/post/new
    defaults: { _controller: KailabBackendBundle:BlogPost:new }

backend_blog_post_edit:
    pattern:  /blog/post/edit/{id}
    defaults: { _controller: KailabBackendBundle:BlogPost:edit }

backend_blog_post_image:
    pattern:  /blog/post/{id}/image
    defaults: { _controller: KailabBackendBundle:BlogPost:image }

backend_blog_post_save:
    pattern:  /blog/post/save
    defaults: { _controller: KailabBackendBundle:BlogPost:save }

backend_blog_post_delete:
    pattern:  /blog/post/delete/{id}
    defaults: { _controller: KailabBackendBundle:BlogPost:delete }

backend_blog_post_toggle:
    pattern:  /blog/post/toggle/{id}
    defaults: { _controller: KailabBackendBundle:BlogPost:toggle }

# blog category

backend_blog_category_list:
    pattern:  /blog/category
    defaults: { _controller: KailabBackendBundle:BlogCategory:index }

backend_blog_category_new:
    pattern:  /blog/category/new
    defaults: { _controller: KailabBackendBundle:BlogCategory:new }

backend_blog_category_edit:
    pattern:  /blog/category/edit/{id}
    defaults: { _controller: KailabBackendBundle:BlogCategory:edit }

backend_blog_category_save:
    pattern:  /blog/category/save
    defaults: { _controller: KailabBackendBundle:BlogCategory:save }

backend_blog_category_delete:
    pattern:  /blog/category/delete/{id}
    defaults: { _controller: KailabBackendBundle:BlogCategory:delete }

backend_blog_category_up:
    pattern:  /blog/category/up/{id}
    defaults: { _controller: KailabBackendBundle:BlogCategory:up }

backend_blog_category_down:
    pattern:  /blog/category/down/{id}
    defaults: { _controller: KailabBackendBundle:BlogCategory:down }

backend_blog_category_toggle:
    pattern:  /blog/category/toggle/{id}
    defaults: { _controller: KailabBackendBundle:BlogCategory:toggle }

# blog comment

backend_blog_comment_list:
    pattern:  /blog/comment
    defaults: { _controller: KailabBackendBundle:BlogComment:index }

backend_blog_comment_new:
    pattern:  /blog/comment/new
    defaults: { _controller: KailabBackendBundle:BlogComment:new }

backend_blog_comment_edit:
    pattern:  /blog/comment/edit/{id}
    defaults: { _controller: KailabBackendBundle:BlogComment:edit }

backend_blog_comment_save:
    pattern:  /blog/comment/save
    defaults: { _controller: KailabBackendBundle:BlogComment:save }

backend_blog_comment_delete:
    pattern:  /blog/comment/delete/{id}
    defaults: { _controller: KailabBackendBundle:BlogComment:delete }

backend_blog_comment_toggle:
    pattern:  /blog/comment/toggle/{id}
    defaults: { _controller: KailabBackendBundle:BlogComment:toggle }

# question

backend_question_list:
    pattern:  /question
    defaults: { _controller: KailabBackendBundle:Question:index }

backend_question_new:
    pattern:  /question/new
    defaults: { _controller: KailabBackendBundle:Question:new }

backend_question_edit:
    pattern:  /question/edit/{id}
    defaults: { _controller: KailabBackendBundle:Question:edit }

backend_question_save:
    pattern:  /question/save
    defaults: { _controller: KailabBackendBundle:Question:save }

backend_question_delete:
    pattern:  /question/delete/{id}
    defaults: { _controller: KailabBackendBundle:Question:delete }

backend_question_toggle:
    pattern:  /question/toggle/{id}
    defaults: { _controller: KailabBackendBundle:Question:toggle }

backend_question_up:
    pattern:  /question/up/{id}
    defaults: { _controller: KailabBackendBundle:Question:up }

backend_question_down:
    pattern:  /question/down/{id}
    defaults: { _controller: KailabBackendBundle:Question:down }

# user

backend_user_list:
    pattern:  /user
    defaults: { _controller: KailabBackendBundle:User:index }

backend_user_new:
    pattern:  /user/new
    defaults: { _controller: KailabBackendBundle:User:new }

backend_user_edit:
    pattern:  /user/edit/{id}
    defaults: { _controller: KailabBackendBundle:User:edit }

backend_user_save:
    pattern:  /user/save
    defaults: { _controller: KailabBackendBundle:User:save }

backend_user_delete:
    pattern:  /user/delete/{id}
    defaults: { _controller: KailabBackendBundle:User:delete }

backend_user_toggle:
    pattern:  /user/toggle/{id}
    defaults: { _controller: KailabBackendBundle:User:toggle }

# fos user bundle

# app/config/routing.yml
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /user/profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /user/register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /user/resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /user/password
