homepage:
    pattern:  /
    defaults: { _controller: KailabFrontendBundle:Default:index }
    
backend:
    prefix:   /admin
    resource: "@KailabBackendBundle/Resources/config/routing.yml"
        
KailabBackendBundle:
    resource: "@KailabBackendBundle/Controller/"
    type:     annotation
    prefix:   /admin

KaikabFrontendBundle:
    resource: "@KailabFrontendBundle/Controller/"
    type:     annotation

