frontend_homepage:
    pattern:  /
    defaults: { _controller: KailabFrontendBundle:Default:index }

frontend_slide:
    pattern:  /slide/{id}.png
    defaults: { _controller: KailabFrontendBundle:Default:slide }

frontend_about:
    pattern:  /about
    defaults: { _controller: KailabFrontendBundle:Default:about }

frontend_legal:
    pattern:  /legal
    defaults: { _controller: KailabFrontendBundle:Default:legal }

frontend_faq:
    pattern:  /faq
    defaults: { _controller: KailabFrontendBundle:Default:faq }

frontend_contact:
    pattern:  /contact
    defaults: { _controller: KailabFrontendBundle:Default:contact }

frontend_blog:
    pattern:  /blog
    defaults: { _controller: KailabFrontendBundle:Blog:index }

frontend_blog_page:
    pattern:  /blog/{page}
    defaults: { _controller: KailabFrontendBundle:Blog:index, page: 1 }
    requirements:
        page:  \d+

frontend_blog_post:
    pattern:  /blog/post/{id}
    defaults: { _controller: KailabFrontendBundle:Blog:post }
    requirements:
        id:  \d+

frontend_blog_post_image:
    pattern:  /blog/post/{id}/image.png
    defaults: { _controller: KailabFrontendBundle:Blog:postImage }

frontend_blog_post_image_small:
    pattern:  /blog/post/{id}/image_small.png
    defaults: { _controller: KailabFrontendBundle:Blog:postImageSmall }

frontend_blog_category:
    pattern:  /blog/category/{id}
    defaults: { _controller: KailabFrontendBundle:Blog:category }
    requirements:
        id:  \d+

frontend_technologies:
    pattern:  /tech
    defaults: { _controller: KailabFrontendBundle:Technology:index }

frontend_technology_icon:
    pattern:  /tech/icon/{id}.png
    defaults: { _controller: KailabFrontendBundle:Technology:icon }

frontend_technology_image:
    pattern:  /tech/image/{id}.png
    defaults: { _controller: KailabFrontendBundle:Technology:image }

frontend_applications:
    pattern:  /apps
    defaults: { _controller: KailabFrontendBundle:Applications:index }

frontend_videogames:
    pattern:  /games
    defaults: { _controller: KailabFrontendBundle:Videogames:index }

frontend_screenshot_item:
    pattern:  /screenshot/item/{id}.png
    defaults: { _controller: KailabFrontendBundle:Screenshot:item }

frontend_screenshot_big:
    pattern:  /screenshot/big/{id}.png
    defaults: { _controller: KailabFrontendBundle:Screenshot:big }

frontend_screenshot_small:
    pattern:  /screenshot/small/{id}.png
    defaults: { _controller: KailabFrontendBundle:Screenshot:small }

frontend_screenshot_full:
    pattern:  /screenshot/{id}.png
    defaults: { _controller: KailabFrontendBundle:Screenshot:full }

frontend_platform_icon:
    pattern:  /platform/icon/{id}.png
    defaults: { _controller: KailabFrontendBundle:Platform:icon }
