frontend_homepage:
    pattern:  /
    defaults: { _controller: KailabFrontendBundle:Default:index }

frontend_slide:
    pattern:  /slide/{id}
    defaults: { _controller: KailabFrontendBundle:Default:slide }

frontend_locale_homepage:
    pattern:  /{_locale}
    defaults: { _controller: KailabFrontendBundle:Default:index }

frontend_about:
    pattern:  /{_locale}/about
    defaults: { _controller: KailabFrontendBundle:Default:about }

frontend_legal:
    pattern:  /{_locale}/legal
    defaults: { _controller: KailabFrontendBundle:Default:legal }

frontend_faq:
    pattern:  /{_locale}/faq
    defaults: { _controller: KailabFrontendBundle:Default:faq }

frontend_contact:
    pattern:  /{_locale}/contact
    defaults: { _controller: KailabFrontendBundle:Default:contact }

frontend_blog:
    pattern:  /{_locale}/blog
    defaults: { _controller: KailabFrontendBundle:Blog:index }

frontend_blog_page:
    pattern:  /{_locale}/blog/{page}
    defaults: { _controller: KailabFrontendBundle:Blog:index, page: 1 }
    requirements:
        page:  \d+

frontend_blog_post:
    pattern:  /{_locale}/blog/post/{id}
    defaults: { _controller: KailabFrontendBundle:Blog:post }
    requirements:
        id:  \d+

frontend_blog_post_image:
    pattern:  /{_locale}/blog/post/{id}/image
    defaults: { _controller: KailabFrontendBundle:Blog:postImage }

frontend_tecnology:
    pattern:  /{_locale}/tec
    defaults: { _controller: KailabFrontendBundle:Tecnology:index }

frontend_applications:
    pattern:  /{_locale}/apps
    defaults: { _controller: KailabFrontendBundle:Applications:index }

frontend_videogames:
    pattern:  /{_locale}/games
    defaults: { _controller: KailabFrontendBundle:Videogames:index }
